---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-api'
  name: '{{.Release.Name}}-saleor-api'
spec:
  ports:
    - name: 'api'
      port: 8000
      targetPort: 8000
  selector:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-api'
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-dashboard'
  name: '{{.Release.Name}}-saleor-dashboard'
spec:
  ports:
    - name: 'dashboard'
      port: 80
      targetPort: 80
  selector:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-dashboard'
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-storefront'
  name: '{{.Release.Name}}-saleor-storefront'
spec:
  ports:
    - name: 'storefront'
      port: 80
      targetPort: 80
  selector:
    app: '{{.Release.Name}}-saleor'
    service: '{{.Release.Name}}-saleor-storefront'
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '120'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '120'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '120'
    nginx.ingress.kubernetes.io/proxy-buffering: 'on'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '8'
    nginx.ingress.kubernetes.io/proxy-buffer-size: '128k'
    nginx.ingress.kubernetes.io/client-body-buffer-size: '1M'
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: '100m'
    nginx.ingress.kubernetes.io/proxy-body-size: '10m'
  labels:
    app: '{{.Release.Name}}-saleor-api'
    service: '{{.Release.Name}}-saleor-ingress'
  name: '{{.Release.Name}}-saleor-api'
spec:
  rules:
    - host: '{{ .Values.saleor.apiIngress }}'
      http:
        paths:
          - backend:
              serviceName: '{{.Release.Name}}-saleor-api'
              servicePort: 8000
            pathType: ImplementationSpecific
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: '{{.Release.Name}}-saleor-dashboard'
    service: '{{.Release.Name}}-saleor-ingress'
  name: '{{.Release.Name}}-saleor-dashboard'
spec:
  rules:
    - host: '{{ .Values.saleor.dashboardIngress }}'
      http:
        paths:
          - backend:
              serviceName: '{{.Release.Name}}-saleor-dashboard'
              servicePort: 80
            pathType: ImplementationSpecific
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: '{{.Release.Name}}-saleor-storefront'
    service: '{{.Release.Name}}-saleor-ingress'
  name: '{{.Release.Name}}-saleor-storefront'
spec:
  rules:
    - host: '{{ .Values.saleor.storefrontIngress }}'
      http:
        paths:
          - backend:
              serviceName: '{{.Release.Name}}-saleor-storefront'
              servicePort: 80
            pathType: ImplementationSpecific
